version: '3.8'

services:
  archipelago-server:
    build: .
    ports:
      - "${ARCHIPELAGO_PORT:-38281}:38281"
    environment:
      - ARCHIPELAGO_PORT=${ARCHIPELAGO_PORT:-38281}
      - ARCHIPELAGO_PASSWORD=${ARCHIPELAGO_PASSWORD:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 38281), timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - archipelago

networks:
  archipelago:
    driver: bridge
