services:
  archipelago-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archipelago-server
    ports:
      - 38281:38281
    volumes:
      - ./games:/app/games
      - ./config:/app/config:ro
    restart: unless-stopped
    networks:
      - archipelago

networks:
  archipelago:
