version: '3.8'

services:
  archipelago-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archipelago-server
    ports:
      - 38281:38281
    volumes:
      - ./games:/app/games:ro
      - ./config:/app/config:ro
      - archipelago_data:/app/data
    restart: unless-stopped
    networks:
      - archipelago-network

volumes:
  archipelago_data:
    driver: local

networks:
  archipelago-network:
    driver: bridge
